spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zheng
    username: root
    password: zz2843517195
  # session expiration time(minutes): two months
  session:
    timeout: 86400
    redis:
      repository-type: default
  # redis config
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
springdoc:
  swagger-ui:
    path: /docs-home.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zheng.usercenter.controller
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false